### ISSUE TITLE
Unable to start forge

### ISSUE THREAD

**Issue by ryanho** [jim60105/docker-stable-diffusion-webui#2]
Using forge or forge-runtime-deps images all get the same error.

> stable-diffusion-webui-forge  | VAE dtype: torch.bfloat16
stable-diffusion-webui-forge  | CUDA Stream Activated:  False
stable-diffusion-webui-forge  | Using xformers cross attention
stable-diffusion-webui-forge  |     import webui
stable-diffusion-webui-forge  |   File "/app/webui.py", line 19, in <module>
stable-diffusion-webui-forge  |     initialize.imports()
stable-diffusion-webui-forge  |   File "/app/modules/initialize.py", line 53, in imports
stable-diffusion-webui-forge  |     from modules import processing, gradio_extensons, ui  # noqa: F401
stable-diffusion-webui-forge  |   File "/app/modules/processing.py", line 18, in <module>
stable-diffusion-webui-forge  |     import modules.sd_hijack
stable-diffusion-webui-forge  |   File "/app/modules/sd_hijack.py", line 5, in <module>
stable-diffusion-webui-forge  |     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
stable-diffusion-webui-forge  |   File "/app/modules/sd_hijack_optimizations.py", line 13, in <module>
stable-diffusion-webui-forge  |     from modules.hypernetworks import hypernetwork
stable-diffusion-webui-forge  |   File "/app/modules/hypernetworks/hypernetwork.py", line 13, in <module>
stable-diffusion-webui-forge  |     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
stable-diffusion-webui-forge  |   File "/app/modules/sd_samplers.py", line 1, in <module>
stable-diffusion-webui-forge  |     from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared
stable-diffusion-webui-forge  |   File "/app/modules/sd_samplers_kdiffusion.py", line 3, in <module>
stable-diffusion-webui-forge  |     import k_diffusion.sampling
stable-diffusion-webui-forge  |   File "/app/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
stable-diffusion-webui-forge  |     from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
stable-diffusion-webui-forge  |   File "/app/repositories/k-diffusion/k_diffusion/evaluation.py", line 6, in <module>
stable-diffusion-webui-forge  |     import clip
stable-diffusion-webui-forge  |   File "/home/1001/.local/lib/python3.10/site-packages/clip/__init__.py", line 1, in <module>
stable-diffusion-webui-forge  |     from .clip import *
stable-diffusion-webui-forge  |   File "/home/1001/.local/lib/python3.10/site-packages/clip/clip.py", line 6, in <module>
stable-diffusion-webui-forge  |     from pkg_resources import packaging
stable-diffusion-webui-forge  | ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/1001/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)
stable-diffusion-webui-forge  | WebUI stopped.
stable-diffusion-webui-forge  | Correcting user data permissions... Please wait a second.
stable-diffusion-webui-forge  | Done.
stable-diffusion-webui-forge exited with code 0

**Comment by jim60105** [comment]
Fixed.
Please pull the new docker image.
