### ISSUE TITLE
forge's ui is broken and can't load some python module when startup

### ISSUE THREAD

**Issue by ryanho** [jim60105/docker-stable-diffusion-webui#5]
UI is totally broken. I think it's because a lot of js files can't be loaded.
![firefox_af9FGBMEyU](https://github.com/user-attachments/assets/aea4df1d-3bb3-4e5d-9a90-e3bc780b0a0f)

When start the container, some python module can't be loaded.
![FireShot Capture 013 - _usr_local_emhttp_webGui_scripts_run_cmd docker logs -f -n 90 stable-_ - 192 168 10 12](https://github.com/user-attachments/assets/d140616c-363c-4f48-b120-be64104819ca)

**Comment by jim60105** [comment]
forge is updating a lot of things, including dependencies, and seems to be unstable.
I have seen other issues in the community, it's best to give it a little more time.
Please use `forge-previous` tag at this moment.

**Comment by zbejas** [comment]
> forge is updating a lot of things, including dependencies, and seems to be unstable. I have seen other issues in the community, it's best to give it a little more time. Please use `forge-previous` tag at this moment.

Any info on when this might be patched?

**Comment by jim60105** [comment]
Alright, maybe I'll handle this tonight.
However, Forge was still updating until 5 minutes ago...

**Comment by jim60105** [comment]
@ryanho This is the actual issue for those 403
Please refer to the answer I provided there:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1220

**Comment by jim60105** [comment]
Oh, I will fix this issue in the image, you don't need to change anything.

**Comment by jim60105** [comment]
Done with https://github.com/jim60105/docker-stable-diffusion-webui/commit/25af8b55d5c61d739a910e31488d9789c4c03948
Try it out with the `forge` tag after CI completes.

(You may need to delete the volume if you're using `runtime-deps` images)
